/**
 * Which boundaries each built-in detector reads at, as the kernel's `DETECTOR_BOUNDARIES` has them.
 * A test holds this to the package, so the count on the costs screen is the package's own.
 */
export const BOUNDARY_NAMES = [
	'user',
	'attachment',
	'voice',
	'slots',
	'context',
	'history',
	'injected',
	'system',
	'repair',
	'live_user',
	'tool_arguments_function',
	'tool_arguments_http',
	'tool_arguments_mcp',
	'tool_arguments_agent',
	'tool_output_function',
	'tool_output_http',
	'tool_output_mcp',
	'tool_output_agent',
	'tool_failure_function',
	'tool_failure_http',
	'tool_failure_mcp',
	'tool_failure_agent',
	'reply',
	'reply_structured',
	'live_reply',
	'thought',
] as const;

export const DETECTOR_CHECKS: readonly { detector: string; at: readonly string[] }[] = [
	{
		detector: 'ids',
		at: [
			'user',
			'attachment',
			'voice',
			'slots',
			'context',
			'history',
			'injected',
			'system',
			'repair',
			'live_user',
			'tool_arguments_function',
			'tool_arguments_http',
			'tool_arguments_mcp',
			'tool_arguments_agent',
			'tool_output_function',
			'tool_output_http',
			'tool_output_mcp',
			'tool_output_agent',
			'tool_failure_function',
			'tool_failure_http',
			'tool_failure_mcp',
			'tool_failure_agent',
			'reply',
			'reply_structured',
			'live_reply',
			'thought',
		],
	},
	{
		detector: 'financial',
		at: [
			'user',
			'attachment',
			'voice',
			'slots',
			'context',
			'history',
			'injected',
			'system',
			'repair',
			'live_user',
			'tool_arguments_function',
			'tool_arguments_http',
			'tool_arguments_mcp',
			'tool_arguments_agent',
			'tool_output_function',
			'tool_output_http',
			'tool_output_mcp',
			'tool_output_agent',
			'tool_failure_function',
			'tool_failure_http',
			'tool_failure_mcp',
			'tool_failure_agent',
			'reply',
			'reply_structured',
			'live_reply',
			'thought',
		],
	},
	{
		detector: 'network',
		at: [
			'user',
			'attachment',
			'voice',
			'slots',
			'context',
			'history',
			'injected',
			'system',
			'repair',
			'live_user',
			'tool_arguments_function',
			'tool_arguments_http',
			'tool_arguments_mcp',
			'tool_arguments_agent',
			'tool_output_function',
			'tool_output_http',
			'tool_output_mcp',
			'tool_output_agent',
			'tool_failure_function',
			'tool_failure_http',
			'tool_failure_mcp',
			'tool_failure_agent',
			'reply',
			'reply_structured',
			'live_reply',
			'thought',
		],
	},
	{
		detector: 'credentials',
		at: [
			'user',
			'attachment',
			'voice',
			'slots',
			'context',
			'history',
			'injected',
			'system',
			'repair',
			'live_user',
			'tool_arguments_function',
			'tool_arguments_http',
			'tool_arguments_mcp',
			'tool_arguments_agent',
			'tool_output_function',
			'tool_output_http',
			'tool_output_mcp',
			'tool_output_agent',
			'tool_failure_function',
			'tool_failure_http',
			'tool_failure_mcp',
			'tool_failure_agent',
			'reply',
			'reply_structured',
			'live_reply',
			'thought',
		],
	},
	{
		detector: 'injection',
		at: [
			'user',
			'attachment',
			'voice',
			'slots',
			'context',
			'history',
			'injected',
			'system',
			'repair',
			'live_user',
			'tool_arguments_function',
			'tool_arguments_http',
			'tool_arguments_mcp',
			'tool_arguments_agent',
			'tool_output_function',
			'tool_output_http',
			'tool_output_mcp',
			'tool_output_agent',
			'tool_failure_function',
			'tool_failure_http',
			'tool_failure_mcp',
			'tool_failure_agent',
			'reply',
			'reply_structured',
			'live_reply',
			'thought',
		],
	},
	{
		detector: 'tool_instructions',
		at: [
			'tool_output_function',
			'tool_output_http',
			'tool_output_mcp',
			'tool_output_agent',
			'tool_failure_function',
			'tool_failure_http',
			'tool_failure_mcp',
			'tool_failure_agent',
		],
	},
	{
		detector: 'canary_leak',
		at: [
			'tool_arguments_function',
			'tool_arguments_http',
			'tool_arguments_mcp',
			'tool_arguments_agent',
			'reply',
			'reply_structured',
			'live_reply',
			'thought',
		],
	},
	{
		detector: 'prompt_leak',
		at: [
			'tool_arguments_function',
			'tool_arguments_http',
			'tool_arguments_mcp',
			'tool_arguments_agent',
			'reply',
			'reply_structured',
			'live_reply',
			'thought',
		],
	},
	{ detector: 'marker_leak', at: ['reply', 'reply_structured', 'live_reply', 'thought'] },
	{ detector: 'ungiven_images', at: ['reply', 'reply_structured', 'live_reply', 'thought'] },
	{ detector: 'ungiven_links', at: ['reply', 'reply_structured', 'live_reply', 'thought'] },
	{ detector: 'tool_leak', at: ['reply', 'reply_structured', 'live_reply', 'thought'] },
];
