/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme.ts
 * Command: astryx theme build app/theme.ts --out app/built/theme.css
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface HeadingTypeMap {
    'wordmark': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/Card' {
  interface CardVariantMap {
    'still': true;
    'glass': true;
  }
}

declare module '@astryxdesign/core/Section' {
  interface SectionVariantMap {
    'raised': true;
  }
}
