/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme.ts
 * Command: astryx theme build app/theme.ts --out app/built/theme.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./theorem-site.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const tablerIcons: IconRegistry;
export declare const theoremSiteTheme: DefinedTheme;
