import type { DocArticleDef } from '../schema';

export const modalities: DocArticleDef = {
	slug: 'modalities',
	updated: '2026-09-30',
	title: 'Choosing a modality',
	entry: 'src/kernel/registry/profiles.ts',
	summary:
		'The profile type is the modality \u2014 it locks which blocks you may author and which pins you must set. Six types, one contract.',
	cover: {
		src: '/imagery/th30_wideorchard.png',
		alt: 'A wide orchard',
	},
	suggest: { rank: 2 },
	questions: [{ question: 'What does each profile type carry, and what are its limits?' }],
	blocks: [
		{
			id: 'lede',
			kind: 'lede',
			text: 'The profile\u2019s `type` is the modality. It locks which blocks you may author and which pins you must set. Pick the type that matches the agent; the field pages deepen each block.',
		},
		{
			id: 'text',
			kind: 'prose',
			title: 'Text',
			text: [
				'Turn-based agent: identity with system, models, tools, turn inputs, optional outputs and turn behaviour.',
				'Protocols `openAi` or `geminiInteractions`. May set `inputs.voice`, `tools.t1Policy` / `t2Loader`, and model compaction. No `image` / `speech` / `live` / `decision` pins.',
			].join('\n\n'),
		},
		{
			id: 'text-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const agent = defineProfile({',
					"\ttype: 'text',",
					"\tid: 'harbor.desk',",
					'\tidentity: {',
					"\t\thandle: 'desk',",
					"\t\tsystem: 'You are Harbor front desk for shippers.',",
					'\t},',
					'\tmodels: {',
					'\t\tmain: {',
					"\t\t\tprotocol: 'openAi',",
					"\t\t\tprovider: 'openrouter',",
					"\t\t\tapiId: 'openrouter/free',",
					'\t\t},',
					'\t},',
					"\ttools: { allow: ['harbor.holdStatus'] },",
					'\tinputs: {',
					"\t\tattachments: { accept: ['image/*', 'application/pdf'] },",
					'\t\tmaxFiles: 4,',
					'\t\tmaxBytes: 5_000_000,',
					'\t\tmaxTurnBytes: 12_000_000,',
					'\t},',
					"\toutputs: { structured: 'harbor.desk.reply' },",
					'\tturnBehaviour: { allowSteering: true },',
					'\tguardrails: {',
					'\t\tsanitizeInput: true,',
					'\t\tredactSensitive: true,',
					'\t\tcanary: true,',
					'\t},',
					'})',
				].join('\n'),
			},
		},
		{
			id: 'image',
			kind: 'prose',
			title: 'Image',
			text: [
				'Same spine as text, plus a required `image` pin. Attachments stay in the image accept set; no voice channel; no mid-turn steering.',
				'No `inputs.voice`, no `allowSteering`. `image.*` fields you omit follow the provider default. Protocols `openAi` or `geminiInteractions`.',
			].join('\n\n'),
		},
		{
			id: 'image-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const illustrator = defineProfile({',
					"\ttype: 'image',",
					"\tid: 'harbor.label',",
					'\tidentity: {',
					"\t\thandle: 'label',",
					"\t\tsystem: 'Compose clear shipping-label art.',",
					'\t},',
					'\tmodels: {',
					'\t\tmain: {',
					"\t\t\tprotocol: 'geminiInteractions',",
					"\t\t\tprovider: 'google',",
					"\t\t\tapiId: 'gemini-3.1-flash-image-preview',",
					"\t\t\tkey: 'slotA',",
					'\t\t},',
					'\t},',
					'\ttools: { allow: [] },',
					'\tinputs: {',
					"\t\tattachments: { accept: ['image/*', 'application/pdf'] },",
					'\t\tmaxFiles: 4,',
					'\t\tmaxBytes: 5_000_000,',
					'\t\tmaxTurnBytes: 12_000_000,',
					'\t},',
					'\timage: {',
					"\t\taspectRatio: '1:1',",
					"\t\tmimeType: 'image/png',",
					'\t},',
					'})',
				].join('\n'),
			},
		},
		{
			id: 'speech',
			kind: 'prose',
			title: 'Speech',
			text: [
				'Transcript in, audio out. Handle only \u2014 no system line, no tools, no `inputs` block. Required `speech` pin. Canary stays off.',
				'No `identity.system`, no `tools`, no `inputs`. Omit `speech.format` and the provider picks; author `pcm` for WAV, `mp3` only with protocol `openAi`. Protocols `openAi` or `geminiInteractions`.',
			].join('\n\n'),
		},
		{
			id: 'speech-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const announcer = defineProfile({',
					"\ttype: 'speech',",
					"\tid: 'harbor.announce',",
					"\tidentity: { handle: 'announce' },",
					'\tmodels: {',
					'\t\tmain: {',
					"\t\t\tprotocol: 'geminiInteractions',",
					"\t\t\tprovider: 'google',",
					"\t\t\tapiId: 'gemini-3.1-flash-tts-preview',",
					"\t\t\tkey: 'slotA',",
					'\t\t},',
					'\t},',
					'\tspeech: {',
					"\t\tvoice: 'Kore',",
					'\t},',
					'\tguardrails: { canary: false },',
					'})',
				].join('\n'),
			},
		},
		{
			id: 'live',
			kind: 'prose',
			title: 'Live',
			text: [
				'Realtime session. `geminiLive` only. Tools are an allow list (no T1/T2). Ingress lives under `live`; no turn `inputs` or `outputs`. Session resume is `live.sessionResumption`, not `turnBehaviour.resumption`.',
				'Omit a channel and audio/video default on, text off \u2014 at least one channel must end up on. No `outputs`. No `models.*.compaction` (use `live.contextCompression` when you need a window).',
			].join('\n\n'),
		},
		{
			id: 'live-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const line = defineProfile({',
					"\ttype: 'live',",
					"\tid: 'harbor.line',",
					'\tidentity: {',
					"\t\thandle: 'line',",
					"\t\tsystem: 'You are on a live call with a Harbor shipper.',",
					'\t},',
					'\tmodels: {',
					'\t\tmain: {',
					"\t\t\tprotocol: 'geminiLive',",
					"\t\t\tprovider: 'google',",
					"\t\t\tapiId: 'gemini-3.1-flash-live-preview',",
					"\t\t\tkey: 'slotA',",
					'\t\t},',
					'\t},',
					"\ttools: { allow: ['harbor.holdStatus'] },",
					'\tlive: {',
					'\t\tingress: { audio: true, video: false, text: true },',
					'\t\tsessionResumption: true,',
					'\t},',
					'\tturnBehaviour: { allowSteering: true },',
					'})',
				].join('\n'),
			},
		},
		{
			id: 'decision',
			kind: 'prose',
			title: 'Decision',
			text: [
				"Structured answers over JSON state. One model by `apiId` only (no protocol/provider). Handle only. Required `decision.contract`. `inputs.state: 'json'`.",
				'No tools, no turn outputs, no turn behaviour, no `identity.system`. `decision.contract` is a host span id \u2014 not the prompt. Questions and state ride on the `runDecision` request ([Running a turn](/docs/runner)).',
			].join('\n\n'),
		},
		{
			id: 'decision-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const router = defineProfile({',
					"\ttype: 'decision',",
					"\tid: 'harbor.route',",
					"\tidentity: { handle: 'route' },",
					'\tmodels: {',
					"\t\tjev: { apiId: 'jev-latest' },",
					'\t},',
					"\tinputs: { state: 'json' },",
					"\tdecision: { contract: 'harbor.route.v1' },",
					'\tguardrails: {',
					'\t\tdisclosure: { enforce: true },',
					'\t},',
					'})',
				].join('\n'),
			},
		},
		{
			id: 'host',
			kind: 'prose',
			title: 'Host',
			text: [
				'Tools only \u2014 no identity, no models, no turn inputs or outputs.',
				'Guardrails here are sanitise, redact, and network only. Call tools with `invokeTool` ([Running a turn](/docs/runner)).',
			].join('\n\n'),
		},
		{
			id: 'host-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const toolbox = defineProfile({',
					"\ttype: 'host',",
					"\tid: 'harbor.tools',",
					"\ttools: { allow: ['harbor.holdStatus', 'haversine_distance'] },",
					'\tguardrails: {',
					'\t\tsanitizeInput: true,',
					'\t\tredactSensitive: true,',
					'\t},',
					'})',
				].join('\n'),
			},
		},
	],
};
