import type { DocArticleDef } from '../schema';

export const modalities: DocArticleDef = {
	slug: 'modalities',
	updated: '2026-10-05',
	title: 'Choosing a modality',
	entry: 'src/kernel/registry/profiles.ts',
	covers: ['src/kernel/registry/profiles.ts', 'src/kernel/schema.ts'],
	summary:
		'Pick the profile type that fits your agent: text, image, speech, live, decision or host. Each type has its own fields and its own door.',
	cover: {
		src: '/imagery/th30_dyevats.png',
		alt: 'Round vats of blue dye, from above',
		position: '44% 82%',
	},
	suggest: { rank: 2 },
	questions: [
		{ question: 'Which profile type fits my agent?' },
		{ question: 'What must each type set, and what can it not set?' },
	],
	blocks: [
		{
			id: 'lede',
			kind: 'lede',
			text: [
				'Set `type` on the profile to say what the agent does. The type is the modality. It is the first choice you make, because it decides which fields you may set and which function runs the agent.',
				'`defineProfile` throws when a profile sets a field its type does not allow or leaves out a field its type needs. The error appears when your application starts, not in the middle of a turn.',
			].join('\n\n'),
		},
		{
			id: 'choose',
			kind: 'table',
			title: 'Pick a type',
			text: [
				'The agent should | Type | Run it with',
				'--- | --- | ---',
				'Chat in turns and call tools | `text` | `runTurn`',
				'Return a picture | `image` | `runTurn`',
				'Read a transcript aloud | `speech` | `runTurn`',
				'Hold a realtime voice or video call | `live` | `runSession`',
				'Answer typed questions about JSON state | `decision` | `runDecision`',
				'Run your tools with no model | `host` | `invokeTool`',
			].join('\n'),
		},
		{
			id: 'choose-note',
			kind: 'callout',
			tone: 'note',
			text: 'Every example on this page sets `key`. That field names the vault slot that holds the provider key ([Binding models](/docs/models)). If you are not sure, start with `text`.',
		},
		{
			id: 'text',
			kind: 'prose',
			title: 'Text',
			text: [
				'Use `text` for an agent that chats in turns and may call tools. Run it with `runTurn`.',
				'- Must set: `identity`, `models`, `tools` and `inputs`.\n- May set: `outputs` and `turnBehaviour`.\n- Protocol: `openAi` or `geminiInteractions`.',
			].join('\n\n'),
		},
		{
			id: 'text-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const desk = defineProfile({',
					"\ttype: 'text',",
					"\tid: 'harbor.desk',",
					"\tkey: 'openrouter',",
					"\tidentity: { handle: 'desk', system: 'You are the Harbor front desk.' },",
					'\tmodels: {',
					"\t\tmain: { protocol: 'openAi', provider: 'openrouter', apiId: 'openrouter/free' },",
					'\t},',
					'\ttools: { allow: [] },',
					'\tinputs: {},',
					'})',
				].join('\n'),
			},
		},
		{
			id: 'image',
			kind: 'prose',
			title: 'Image',
			text: [
				'Use `image` for an agent that returns a picture. Run it with `runTurn`.',
				'- Must set: the same fields as `text`, plus `image`.\n- Cannot set: `inputs.voice`, `outputs.structured` or `turnBehaviour.allowSteering`.\n- Protocol: `openAi` or `geminiInteractions`.',
			].join('\n\n'),
		},
		{
			id: 'image-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const illustrator = defineProfile({',
					"\ttype: 'image',",
					"\tid: 'harbor.label',",
					"\tkey: 'google',",
					"\tidentity: { handle: 'label', system: 'Draw clear shipping-label art.' },",
					'\tmodels: {',
					'\t\tmain: {',
					"\t\t\tprotocol: 'geminiInteractions',",
					"\t\t\tprovider: 'google',",
					'\t\t\tpersistViaInteractionId: false,',
					"\t\t\tapiId: 'gemini-2.5-flash-image',",
					'\t\t},',
					'\t},',
					'\ttools: { allow: [] },',
					'\tinputs: {},',
					"\timage: { aspectRatio: '1:1', mimeType: 'image/png' },",
					'})',
				].join('\n'),
			},
		},
		{
			id: 'speech',
			kind: 'prose',
			title: 'Speech',
			text: [
				'Use `speech` to read a transcript aloud. Run it with `runTurn`. The input text is the transcript.',
				'- Must set: `identity` with a `handle` only, `models` and `speech`.\n- Cannot set: `identity.system`, `tools` or `inputs`.\n- Canary: a speech profile always stores `guardrails.canary: false`, because the reply is audio and not text.',
				'`speech.format` is `pcm` or `mp3`. `pcm` is delivered as WAV. `mp3` needs protocol `openAi`.',
			].join('\n\n'),
		},
		{
			id: 'speech-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const announcer = defineProfile({',
					"\ttype: 'speech',",
					"\tid: 'harbor.announce',",
					"\tkey: 'google',",
					"\tidentity: { handle: 'announce' },",
					'\tmodels: {',
					'\t\tmain: {',
					"\t\t\tprotocol: 'geminiInteractions',",
					"\t\t\tprovider: 'google',",
					'\t\t\tpersistViaInteractionId: false,',
					"\t\t\tapiId: 'gemini-3.1-flash-tts-preview',",
					'\t\t},',
					'\t},',
					"\tspeech: { voice: 'Kore' },",
					'})',
				].join('\n'),
			},
		},
		{
			id: 'live',
			kind: 'prose',
			title: 'Live',
			text: [
				'Use `live` for a realtime voice or video call. Run it with `runSession`.',
				'- Must set: `identity`, `models`, `tools` and `live`.\n- Cannot set: `inputs` or `outputs`. `live.ingress` replaces `inputs`.\n- Protocol: `geminiLive` only.',
				'If you leave out an ingress channel, audio and video default to on and text to off. At least one channel must be on.',
				'Use `live.sessionResumption` in place of `turnBehaviour.resumption`. Use `live.contextCompression` in place of model `compaction`.',
			].join('\n\n'),
		},
		{
			id: 'live-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const line = defineProfile({',
					"\ttype: 'live',",
					"\tid: 'harbor.line',",
					"\tkey: 'google',",
					"\tidentity: { handle: 'line', system: 'You are on a live call with a Harbor shipper.' },",
					'\tmodels: {',
					"\t\tmain: { protocol: 'geminiLive', provider: 'google', apiId: 'gemini-3.1-flash-live-preview' },",
					'\t},',
					'\ttools: { allow: [] },',
					'\tlive: {',
					'\t\tingress: { audio: true, video: false, text: true },',
					'\t\tsessionResumption: true,',
					'\t},',
					'})',
				].join('\n'),
			},
		},
		{
			id: 'decision',
			kind: 'prose',
			title: 'Decision',
			text: [
				'Use `decision` to get typed answers about JSON state. Run it with `runDecision`.',
				'- Must set: `identity` with a `handle` only, one model with protocol `decision`, `inputs.state: "json"` and `decision.contract`.\n- Cannot set: `identity.system`, `tools`, `outputs` or `turnBehaviour`.\n- Provider: `typesafe` or `openrouter`.',
				'The contract is your own id for the decision. Theorem records it on the trace and does not send it to the model. The questions and the state travel on the `runDecision` request ([Running a turn](/docs/runner)).',
			].join('\n\n'),
		},
		{
			id: 'decision-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const router = defineProfile({',
					"\ttype: 'decision',",
					"\tid: 'harbor.route',",
					"\tkey: 'typesafe',",
					"\tidentity: { handle: 'route' },",
					'\tmodels: {',
					"\t\tjev: { protocol: 'decision', provider: 'typesafe', apiId: 'jev-latest' },",
					'\t},',
					"\tinputs: { state: 'json' },",
					"\tdecision: { contract: 'harbor.route.v1' },",
					'})',
				].join('\n'),
			},
		},
		{
			id: 'host',
			kind: 'prose',
			title: 'Host',
			text: [
				'Use `host` to run registered tools with no model, for example from your own API route. Run it with `invokeTool` ([Running a turn](/docs/runner)).',
				'- Must set: `tools`.\n- Cannot set: `identity`, `models`, `inputs` or `outputs`.\n- Guardrails: only `sanitizeInput`, `redactSensitive` and `network`.',
			].join('\n\n'),
		},
		{
			id: 'host-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const toolbox = defineProfile({',
					"\ttype: 'host',",
					"\tid: 'harbor.tools',",
					"\ttools: { allow: ['haversine_distance'] },",
					'\tguardrails: { sanitizeInput: true, redactSensitive: true },',
					'})',
				].join('\n'),
			},
		},
	],
};
