import type { DocArticleDef } from '../schema';

export const runner: DocArticleDef = {
	slug: 'runner',
	updated: '2026-10-01',
	title: 'Running a turn',
	entry: 'src/kernel/engine/runner/mod.ts',
	summary:
		'Which door to call, what to pass, what the stream yields, and how a paused tool resumes. Four doors share one event family.',
	cover: {
		src: '/imagery/th30_poppies.png',
		alt: 'A field of poppies',
		position: '0% 8%',
	},
	suggest: { rank: 3 },
	questions: [
		{ question: 'Which door do I call, and what must I pass?' },
		{ question: 'What comes back on the stream, and where does a gate show up?' },
	],
	blocks: [
		{
			id: 'lede',
			kind: 'lede',
			text: 'You already chose a modality and its door. [Choosing a modality](/docs/modalities). This page is the call itself: what to pass, what the stream yields, and how a paused tool resumes. It is not where you author the profile.',
		},
		{
			id: 'run-turn',
			kind: 'prose',
			title: 'runTurn',
			text: [
				'Pass a `TurnRequest` and a `ModelProvider` from `createProvider`. Optional third argument: a trace sink. [Recording traces](/docs/traces).',
				'Required: `profile` (registered id). For a normal user turn, `input` as the profile\u2019s inputs allow ([Declaring inputs](/docs/inputs)).',
				'Use `onStage` when the host must act at a stage. `pre_turn` may inject or abort. `pre_tool` may abort, deny, confirm, or mutate. `post_tool` may inject, abort, deny, or mutate. `before_end` may inject or abort. `post_turn` is read-only. `confirm` on `pre_tool` opens a gate. `mutate` replaces input or raw output and re-validates. Name an inject with `injectId` when you need it on the landing `stage` event.',
				'Also on the request when you need them: `model` / `effort`, `system`, `host`, `signal`, `credentials` / `resolveHost`, `continueFrom` / `continuation` ([Setting turn behaviour](/docs/turn-behaviour)), and trace fields (`traceparent`, `conversationId`, \u2026).',
			].join('\n\n'),
		},
		{
			id: 'run-turn-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					"import { createProvider, runTurn } from '@theoremjs/agents';",
					'',
					'const provider = createProvider(profile, {',
					'\topenAiGateway: { apiKey },',
					'});',
					'',
					'for await (const event of runTurn(',
					'\t{',
					'\t\tprofile: profile.id,',
					"\t\tinput: { text: 'Summarise the brief.' },",
					'\t\tonStage: (ctx) => {',
					"\t\t\tif (ctx.stage === 'pre_tool' && ctx.tool === 'payments.charge') {",
					'\t\t\t\treturn { confirm: true };',
					'\t\t\t}',
					'\t\t},',
					'\t},',
					'\tprovider,',
					')) {',
					"\tif (event.type === 'text') process.stdout.write(event.text);",
					"\tif (event.type === 'done') break;",
					'}',
				].join('\n'),
			},
		},
		{
			id: 'stream-and-gates',
			kind: 'prose',
			title: 'Stream and gates',
			text: [
				'You get `TurnEvent`s until `done` or `error`. Typical path: model output (`text`, `thought`, structured or media), then `tool` / `stage` / `guardrail` as they fire, then `done`.',
				"A gate is not a separate event type. The tool shows phase `gate`, then `done` with `stop.kind: 'gate'`. A normal finish is `completed`. Continue-eligible cuts include `length` and `stream_incomplete` ([Setting turn behaviour](/docs/turn-behaviour)).",
				'Resume with `invokeTool` \u2014 same name and input, the turn\u2019s `callId`, and `resume` when settling. HTTP surfaces that answer gates: [Building the interface](/docs/interface). `guardrail` on the stream is policy, not a stage return \u2014 [Setting guardrails](/docs/guardrails).',
			].join('\n\n'),
		},
		{
			id: 'invoke-resume',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'for await (const event of invokeTool({',
					'\tprofile: profile.id,',
					"\tname: 'payments.charge',",
					'\tcallId,',
					'\tinput,',
					'\tresume: { granted: true },',
					'})) {',
					"\tif (event.type === 'done') break",
					'}',
				].join('\n'),
			},
		},
		{
			id: 'run-session',
			kind: 'prose',
			title: 'runSession',
			text: [
				'Same event family over a long-lived session. Options carry the Gemini transport; optional sink is the third argument.',
				'Gated tools settle on the session (`executeTool` / answer), not turn `invokeTool`. `onStage` is fixed at open. `gateTtlMs` defaults to thirty minutes. Use `snapshot` when a relay opens with tools resolved elsewhere.',
			].join('\n\n'),
		},
		{
			id: 'run-session-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const session = await runSession(',
					"\t{ profile: profile.id, system: 'Be brief.' },",
					'\t{ gemini },',
					')',
					'',
					'for await (const event of session.events()) {',
					'\t/* \u2026 */',
					'}',
				].join('\n'),
			},
		},
		{
			id: 'run-decision',
			kind: 'prose',
			title: 'runDecision',
			text: 'State and questions in; answers out. No transcript stream. Key or vault \u2014 and optional sink \u2014 sit on **options**.',
		},
		{
			id: 'run-decision-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					'const result = await runDecision(',
					'\t{',
					'\t\tprofile: profile.id,',
					"\t\tstate: { ticket: 'T-1042', priority: 'high' },",
					'\t\tquestions: {',
					'\t\t\troute: {',
					"\t\t\t\ttype: 'choice',",
					"\t\t\t\tinstructions: 'Where should this ticket go?',",
					'\t\t\t\tcriteria: {',
					"\t\t\t\t\tbilling: 'Payment or invoice.',",
					"\t\t\t\t\tsupport: 'Product help.',",
					"\t\t\t\t\tignore: 'Noise; no action.',",
					'\t\t\t\t},',
					'\t\t\t},',
					'\t\t},',
					'\t},',
					'\t{ apiKey },',
					')',
				].join('\n'),
			},
		},
		{
			id: 'invoke-alone',
			kind: 'prose',
			title: 'invokeTool alone',
			text: 'Run a registered tool with no model in front (or resume as above). `onStage` sees `pre_tool` / `post_tool` only.',
		},
		{
			id: 'what-breaks',
			kind: 'prose',
			title: 'What breaks',
			text: [
				'Profile or tools not registered. Empty provider credentials when the run needs them \u2014 [Binding models](/docs/models). A stage action the matrix does not allow. A live gate answered after TTL \u2014 `session.gate_expired`.',
				'Wrong door is a modality mistake \u2014 [Choosing a modality](/docs/modalities).',
			].join('\n\n'),
		},
	],
};
