import type { DocArticleDef } from '../schema';

export const runner: DocArticleDef = {
	slug: 'runner',
	updated: '2026-10-05',
	title: 'Running a turn',
	entry: 'src/kernel/engine/runner/mod.ts',
	covers: [
		'src/kernel/engine/runner',
		'src/kernel/engine/decision.ts',
		'src/kernel/engine/session',
		'src/kernel/tools/invoke.ts',
		'src/kernel/stages.ts',
	],
	summary:
		'Call the door that matches your profile type, read the event stream, and resume a tool that paused for approval.',
	cover: {
		src: '/imagery/th30_poppies.png',
		alt: 'A field of poppies',
		position: '0% 8%',
	},
	suggest: { rank: 3 },
	blocks: [
		{
			id: 'lede',
			kind: 'lede',
			text: 'Call `runTurn` to run one turn of a profile and read its events. Text, image and speech profiles use it. Live, decision and host profiles each have their own door ([Choosing a modality](/docs/modalities)).',
		},
		{
			id: 'run-turn',
			kind: 'prose',
			title: 'Run a turn',
			text: [
				'Pass a request and a provider. Create the provider with `createProvider` and a vault. The vault maps each key slot to its secret. The profile names the slot in `key`.',
				'The request needs `profile`, the id of a registered profile. Add `input` for a user turn ([Declaring inputs](/docs/inputs)). The optional third argument is a trace sink ([Recording traces](/docs/traces)).',
			].join('\n\n'),
		},
		{
			id: 'run-turn-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				code: [
					"import { createProvider, runTurn } from '@theoremjs/agents';",
					'',
					'const vault = { openrouter: process.env.OPENROUTER_API_KEY };',
					'const provider = createProvider(profile, { vault });',
					'',
					'for await (const event of runTurn(',
					"\t{ profile: profile.id, input: { text: 'Where is hold H-2291?' } },",
					'\tprovider,',
					')) {',
					"\tif (event.type === 'text') console.log(event.text);",
					'}',
				].join('\n'),
			},
		},
		{
			id: 'request-fields',
			kind: 'prose',
			title: 'Set more on the request',
			text: 'The request also takes `model`, `effort`, `system`, `host`, `signal`, `credentials`, `resolveHost`, `continueFrom` and `continuation`. It takes the trace fields `traceparent` and `conversationId`. See [Setting turn behaviour](/docs/turn-behaviour) for `continueFrom`.',
		},
		{
			id: 'history',
			kind: 'prose',
			title: 'Continue a chat',
			text: [
				'A turn does not remember the turn before it. Your host stores the chat. To continue, send the earlier messages in `input.history` and the new message in `input.text`.',
				'Each message has a `role` (`user`, `assistant`, `system` or `tool`) and its `content`. A Gemini binding with `persistViaInteractionId: true` is the exception: send `previousInteractionId` and no history ([Binding models](/docs/models)).',
			].join('\n\n'),
		},
		{
			id: 'history-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'runTurn(',
					'\t{',
					"\t\tprofile: 'harbor.desk',",
					'\t\tinput: {',
					'\t\t\thistory: [',
					"\t\t\t\t{ role: 'user', content: 'Where do I find hold H-2291?' },",
					"\t\t\t\t{ role: 'assistant', content: 'It is at bay 4.' },",
					'\t\t\t],',
					"\t\t\ttext: 'When does bay 4 close?',",
					'\t\t},',
					'\t},',
					'\tprovider,',
					')',
				].join('\n'),
			},
		},
		{
			id: 'stages',
			kind: 'prose',
			title: 'Act at a stage',
			text: [
				'Pass `onStage` to run your code at a stage of the turn. Return nothing to observe. Return a result to act. Each stage allows only some results.',
				'`pre_turn` and `before_end` may inject or abort. `pre_tool` may abort, deny, confirm or mutate. `post_tool` may inject, abort, deny or mutate. `post_turn` allows none.',
				'A `confirm` on `pre_tool` opens a gate. A `mutate` replaces the tool input or output, and Theorem validates it again. Set `injectId` to name an inject on the `stage` event.',
			].join('\n\n'),
		},
		{
			id: 'stage-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'request',
				code: [
					'onStage: (ctx) => {',
					"\tif (ctx.stage === 'pre_tool' && ctx.tool === 'payments.charge') {",
					'\t\treturn { confirm: true };',
					'\t}',
					'},',
				].join('\n'),
			},
		},
		{
			id: 'stream',
			kind: 'prose',
			title: 'Read the stream',
			text: [
				'The stream yields `TurnEvent` values until `done` or `error`. Model output comes first as `text`, `thought`, structured data or media. The `tool`, `stage` and `guardrail` events arrive as they fire.',
				'The last event is `done`. Its `stop.kind` is `completed` for a normal finish. A `done` with `length`, `stream_incomplete` or `provider_error` can continue ([Setting turn behaviour](/docs/turn-behaviour)).',
				'A `guardrail` event reports a policy decision. It is not a stage result ([Setting guardrails](/docs/guardrails)).',
			].join('\n\n'),
		},
		{
			id: 'gates',
			kind: 'prose',
			title: 'Resume a gate',
			text: [
				'A gate is not an event type. The tool event shows phase `gate`. Then `done` arrives with `stop.kind` set to `gate`.',
				'Resume with `invokeTool`. Pass the tool name, the input, the turn’s `callId` and `resume`. Set `resume.granted` to `true` to approve or `false` to refuse. HTTP surfaces that answer gates are in [Building the interface](/docs/interface).',
			].join('\n\n'),
		},
		{
			id: 'invoke-resume',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'for await (const event of invokeTool({',
					'\tprofile: profile.id,',
					"\tname: 'payments.charge',",
					'\tcallId,',
					'\tinput,',
					'\tresume: { granted: true },',
					'})) {',
					"\tif (event.type === 'done') break;",
					'}',
				].join('\n'),
			},
		},
		{
			id: 'invoke-alone',
			kind: 'prose',
			title: 'Run a tool without a model',
			text: 'Call `invokeTool` without `resume` and without a `callId` to run a registered tool directly. A host profile uses this door. `onStage` sees `pre_tool` and `post_tool` only.',
		},
		{
			id: 'run-session',
			kind: 'prose',
			title: 'Run a live session',
			text: [
				'Call `runSession` for a live profile. It returns a session. Read its events with `session.events()`. The events use the same family as a turn.',
				'The second argument takes a `vault`. It also takes `gemini`, `openWebSocket`, `gateTtlMs` and `signInGate`.',
				'A live gate settles on the session with `executeTool` or `answerToolCall`, not with `invokeTool`. `onStage` is fixed when the session opens. `gateTtlMs` defaults to 30 minutes. A later decision fails with `session.gate_expired`.',
			].join('\n\n'),
		},
		{
			id: 'run-session-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const session = await runSession(',
					'\t{ profile: profile.id },',
					'\t{ vault: { google: process.env.GEMINI_API_KEY } },',
					');',
					'',
					'for await (const event of session.events()) {',
					"\tif (event.type === 'text') console.log(event.text);",
					'}',
				].join('\n'),
			},
		},
		{
			id: 'run-decision',
			kind: 'prose',
			title: 'Run a decision',
			text: 'Call `runDecision` with JSON state and named questions. It returns validated answers and usage. It has no event stream. Pass the vault in the second argument. An empty slot throws a `DecisionError` (from `@theoremjs/agents/kernel`) with code `authentication`. Its `code` is one of `invalid_request`, `authentication`, `permission`, `rate_limited`, `unavailable`, `network`, `timeout`, `cancelled`, `malformed_response` or `disclosure_blocked`.',
		},
		{
			id: 'run-decision-example',
			kind: 'code',
			source: {
				from: 'literal',
				lang: 'ts',
				frame: 'statements',
				code: [
					'const result = await runDecision(',
					'\t{',
					'\t\tprofile: profile.id,',
					"\t\tstate: { ticket: 'T-1042', priority: 'high' },",
					'\t\tquestions: {',
					'\t\t\troute: {',
					"\t\t\t\ttype: 'choice',",
					"\t\t\t\tinstructions: 'Where should this ticket go?',",
					'\t\t\t\tcriteria: {',
					"\t\t\t\t\tbilling: 'Payment or invoice.',",
					"\t\t\t\t\tsupport: 'Product help.',",
					'\t\t\t\t},',
					'\t\t\t},',
					'\t\t},',
					'\t},',
					'\t{ vault: { typesafe: process.env.TYPESAFE_API_KEY } },',
					');',
				].join('\n'),
			},
		},
		{
			id: 'what-breaks',
			kind: 'table',
			title: 'Fix a failed call',
			text: "What you see | Cause | Fix\n--- | --- | ---\n`TheoremError`, kind `config`: unknown profile | The profile is not registered | Call `registerProfile` first\n`error` event, `errorKind: 'auth'` | The vault has no key in the slot that the profile names | Fill the slot ([Binding models](/docs/models))\n`DecisionError`, code `authentication` | The vault has no key in the slot, or the provider refused it | Fill the slot, or check the key\n`stage` event with `stageWarnings` | A stage returned a result that the stage does not allow | Return only the results in the stage list above\n`session.gate_expired` | A live gate waited longer than `gateTtlMs` | Settle the gate sooner, or raise `gateTtlMs`\n`createProvider`, kind `request` | The profile is `live`, `host` or `decision`, which have no `runTurn` provider | Use `runSession`, `invokeTool` or `runDecision` ([Choosing a modality](/docs/modalities))",
		},
	],
};
